### ISSUE TITLE
Configuration of jupyter_kernels

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinx.ext.jupyter#11]
Currently Jupyter Kernels are configured using the following:

```python
# Configure Jupyter Kernels
jupyter_kernels = {
    "python3": {
        "kernelspec": {
            "display_name": "Python",
            "language": "python3",
            "name": "python3"
            },
        "file_extension": ".py",
    },
    "julia": {
        "kernelspec": {
            "display_name": "Julia 0.6.0",
            "language": "julia",
            "name": "julia-0.6"
            },
        "file_extension": ".jl"
    }
}
```

Should we build this from a list of simpler options? I think this is a good approach for now as it is a complete set of attributes when defining which kernel to use.

**Comment by NickSifniotis** [comment]
Jupiter itself must have the metadata for all its installed kernels lying around somewhere. I'd suggest pulling directly from that data, if possible.

**Comment by mmcky** [comment]
https://github.com/jupyter/jupyter/wiki/Jupyter-kernels

**Comment by mmcky** [comment]
also to get list of installed kernels on a local machine is ``jupyter kernelspec list``

**Comment by mmcky** [comment]
relocated to new repo
