### ISSUE TITLE
Add ability for Welcome Message at Top of Notebook

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/sphinx.ext.jupyter#5]
It would be good to have the ability to add a ``welcome`` message text block at the top of each notebook. 

This will be useful in the beginning to prepend a ``Experimental Feature Notice`` and a link for feedback when we launch on the live site or some other usage. 

Perhaps it should be called ``nb_header_block``

**Comment by NickSifniotis** [comment]
Added ability to add a welcome message block to the top of every Jupyter notebook created by this script.

The content of the block is located in an .RST file. Both the file name and the path to this RST file are configured by entries in the extension's conf.py file.

The file does not need to exist; if the script cannot find the file, it will just build the notebooks without a welcome message.
